feat: add post
NoNameTF/Media_steam_server pull request #4
Opened 2022-05-06 17:51 UTC by izbean

2022-05-07 07:59 UTC, DongHwan-Gim requested changes
그 외 작업 해주신 내용에는 크게 문제가 없는 것 같습니다.
리뷰 남겨 드린 내용 확인 부탁 드립니다.

2022-05-07 07:59 UTC, DongHwan-Gim commented on mediaSteam/src/main/java/com/noname/mediasteam/domain/post/PostComment.java
> +    private User ModifiedUser;
필드명을 ModifiedUser -> modifiedUser 변경하면 좋을 것 같습니다.

2022-05-07 08:12 UTC, izbean commented on mediaSteam/src/main/java/com/noname/mediasteam/domain/post/PostComment.java
> +    private User ModifiedUser;
👍

2022-05-07 08:14 UTC, owen151128 commented on mediaSteam/src/main/java/com/noname/mediasteam/domain/post/PostComment.java
> +    private User ModifiedUser;
@izbean 저거 말고는 문제 없는것 같습니다.
수정 해서 `push` 해주시면 `approve` 해드릴께요!
수고하셨습니다~~

2022-05-15 05:45 UTC, izbean commented on mediaSteam/src/main/java/com/noname/mediasteam/domain/post/PostComment.java
> +    private User ModifiedUser;
수정 완료 했습니다.

2022-05-15 06:18 UTC, DongHwan-Gim approved these changes

2022-05-15 06:24 UTC, merged